### ISSUE TITLE
upload-one only uploads files in the years 2010-2019

### ISSUE THREAD

**Issue by chfoo** [ArchiveTeam/archiveteam-megawarc-factory#2]
`upload-one` [looks for directories with `201`](https://github.com/ArchiveTeam/archiveteam-megawarc-factory/blob/a8cfebae667abaa715dd9d6ffc052c5506f8e43d/upload-one#L43) as part of the filename. Once 2020 rolls around, it may fail.

It's probably best to use a more robust, but portable way, of finding items.

**Comment by km09** [comment]
Fixed by #7
