### ISSUE TITLE
Packer will stop working at the end of 2019

### ISSUE THREAD

**Issue by JustAnotherArchivist** [ArchiveTeam/archiveteam-megawarc-factory#6]
https://github.com/ArchiveTeam/archiveteam-megawarc-factory/blob/923661847fd5a5dfa651467da09be56a4528f7aa/pack-one#L58

Due to that hardcoded `201`, the packer will stop working at the end of this year. I didn't check whether there are more issues like this elsewhere. Needs to be investigated and fixed to avoid nasty surprises in early 2020.

**Comment by km09** [comment]
Fixed by #7
