### ISSUE TITLE
Name collisions in collections due to using timestamp on megawarc

### ISSUE THREAD

**Issue by PhirePhly** [ArchiveTeam/archiveteam-megawarc-factory#7]
The current chunker uses `date +'%Y%m%d%H%M%S'` to give each megawarc a unique identifier, which is ok as long as there is only one chunker running on one rsync target. Since the megawarc name is based on the current time, multiple rsync targets are proving to generate identically named megawarcs.

I'd propose we move to using `uuid` to create unique identifiers for each megawarc. The resulting megawarc names would therefore look like, i.e.: 
`googleplus_2545040a-447b-11e9-8f1f-2b4a7312c1da.megawarc.warc.gz`

Thoughts? Is there any risk in using the dash in an object name? 

This does add the dependency of the `uuid` tool, since it may not be installed on all distros by default.  Edit: It does look like Linux makes version 4 uuids available via `/proc/sys/kernel/random/uuid` - I'm not aware of how portable that is.

This will also close #2 and #6.

**Comment by Arkiver2** [comment]
Fixed with https://github.com/ArchiveTeam/archiveteam-megawarc-factory/commit/f88d14b2a2ab4a2a1749e1f01d045245150cd3c1
